stages:
  preprocess_mnist:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    outs:
    - data/data.pickle
  train_keras:
    cmd: python src/train_keras.py
    deps:
    - src/train_keras.py
    outs:
    - models/mnist_model_5.h5
  evaluate_keras:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    metrics:
    - reports/scores.json:
        cache: false
